# PACKAGES & DATA --------------------------------------------------------------
library(tidyverse)
library(lubridate)
library(httr)
library(jsonlite)

natuy_data <- read_csv("data/NatUY_observations_03-05.csv")
users_dataset <- natuy_data %>% distinct(user_login)

# USERS NATIONALITY ------------------------------------------------------------

# we need to detect those users that are not from Uruguay 
# and remove the data generated by them from our dataset

# Function using iNAT API https://api.inaturalist.org/v1/docs/

getObserversNumObservations <- function(user_login_list, 
                                        place_id=7259){
  
  observers_num_observations <- tibble(user_id = numeric(), 
                                       observations_iNat = numeric(), 
                                       observations_NatUY = numeric(),
                                       species_iNat = numeric(), 
                                       species_NatUY = numeric(), 
                                       user_login = character(),
                                       user_created_at = lubridate::ymd_hms(), 
                                       user_name = character())
  num_results <- 1
  for (user_login in user_login_list) {
    if ((num_results %% 10) + 10 == 10) { 
      Sys.sleep(10) # The API needs a delay because otherwise it gives an error. 
      # Every 10 users, the code stops for 10 second
    }
    call <- str_glue('https://api.inaturalist.org/v1/observations/observers', 
                     '?user_login={user_login}&',
                     'place_id={place_id}')
    
    get_json_call <- GET(url = call) %>%
      content(as = "text") %>%
      fromJSON(flatten = TRUE)
    
    if(!'error' %in% names(get_json_call)) {
      results <- as_tibble(get_json_call$results) 
      observer_num_observations <- 
        tibble(user_id = results$user_id,
               observations_iNat = results$user.observations_count,
               observations_NatUY = results$observation_count,
               species_iNat = results$user.species_count,
               species_NatUY = results$species_count,
               user_login = results$user.login,
               user_created_at = results$user.created_at,
               user_name = results$user.name)
      observers_num_observations <- rbind(observers_num_observations,
                                          observer_num_observations)
      cat(num_results, 'user:', user_login, ',',
          observer_num_observations$observations_iNat, 'observations on iNat', '\n')
    }
    else {
      observer_num_observations <- tibble(user_id = NA, 
                                          observations_iNat = NA, 
                                          observations_NatUY = NA,
                                          species_iNat = NA, 
                                          species_NatUY = NA, 
                                          user_login = user_login,
                                          user_created_at = NA, 
                                          user_name = NA)
      observers_num_observations <- rbind(observers_num_observations,
                                          observer_num_observations)
      cat('user:', user_login, '--> NOT FOUND', '\n')
    }
    num_results <- nrow(observers_num_observations) + 1
  }
  return(observers_num_observations)
}

observers_num_observations <- getObserversNumObservations(users_dataset$user_login)

write_csv(observers_num_observations,'data/observers_num_observations.csv')

# natuy_users <- left_join(as_tibble(users_dataset), 
#                          observers_num_observations %>% 
#                            mutate(user_name=ifelse(user_name=='', NA, user_name))) %>% 
#   mutate(first_record=lubridate::as_datetime(first_record),
#          last_record=lubridate::as_datetime(last_record),
#          user_created_at=lubridate::as_datetime(user_created_at))


# USERS FILTERING --------------------------------------------------------------

## uruguayans in the data
uruguayans <- observers_num_observations %>% 
  mutate(proportion_natuy_inat = round(observations_NatUY*100/observations_iNat, 3),
         uruguayan = ifelse(proportion_natuy_inat>40 , 'yes', 'no')) %>% 
  filter(uruguayan == "yes")

natuy_data <- filter(natuy_data, user_login %in% uruguayans$user_login)


# USERS CATEGORIZATION ---------------------------------------------------------

users_dataset <- natuy_data %>% group_by(user_login) %>% 
  summarise(first_record = min(created_at), 
            last_record = max(created_at), 
            observations = n(), activity_time = 
              difftime(last_record,first_record, 
                       units = "days")+1, 
            observations_by_time = observations/as.numeric(activity_time)) %>% 
  mutate(user_category = ifelse(observations>=1000 & activity_time>=365 &
                                  observations_by_time>=0.6, "expert",
                                ifelse(observations>=50 & activity_time>90 & 
                                         observations_by_time>0.2,
                                       "intermediate", "beginner"))) %>% 
  filter(observations >= 3)

write_csv(users_dataset, "data/users_dataset.csv")

## Users per category

users_dataset %>% group_by(user_category) %>% count() %>% arrange(desc(n))

# user_category     n
# beginner         997
# intermediate     92
# expert           20


natuy_data <- left_join(natuy_data, users_dataset %>% 
                          select(user_login, observations, user_category)) %>% 
  filter(!is.na(user_category))


write_csv(natuy_data, "data/natuy_data.csv")
